name: deploy music_adjaf_api

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build project
        run: ./gradlew build -x test
      - name: Login no Docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build imagem docker
        run: docker build -t pgabrieldevelopoer/music_adjaf_mf3 .
      - name: Push imagem docker
        run: docker push pgabrieldevelopoer/music_adjaf_mf3
