name: deploy music_adjaf_api

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Download project
        run: actions/checkout@v4
      - name: Build project
        run: ./gradlew build -x test
      - name: Adicionando Envs
        run: export ACCESS_KEY=${{secrets.ACCESS_KEY}} \
              BUCKET_NAME=${{secrets.BUCKET_NAME}} \
              MUSIC_DATABASE_HOST=${{secrets.MUSIC_DATABASE_HOST}} \
              MUSIC_DATABASE_PASSWORD=${{secrets.MUSIC_DATABASE_PASSWORD}} \
              MUSIC_DATABASE_USER=${{secrets.MUSIC_DATABASE_USER}} \
              SECRET_KEY=${{secrets.SECRET_KEY}}
      - name: Run app
        run: java -jar build/libs/music_adjaf_mf3-0.0.1.jar

